name = "TMI"
uuid = "582500f6-28c8-4d8f-aabe-b197735ec1d4"
authors = ["G Jake Gebbie"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
